const STORAGE_KEY='h3_project_online_v1';
const mats=[
['m1','Spær','95x45','m',21.50],['m2','Installationslag flunk','45x45','m',9.00],['m3','Flunker','95x45','m',21.50],['m4','Front','95x45','m',21.50],['m5','Lægter','38x73','m',12.50],['m6','Klemlister','50x25','m',4.95],['m7','Kingspan til tag','140 mm','m²',445],['m8','Kingspan installationslag','40 mm','m²',192],['m9','Fermacell','15 mm','stk',120],['m10','Plankekel','295x45','m',80],['m11','Udveksling','120x45','m',26.50],['m12','RAW Roof Pro 400 Undertag','','rulle',2472.53],['m13','Sternbrædder','25x150','m',22.50],['m14','Udhængsbrædder','16x95','m',21.19],['m15','Vindue','60x60','stk',1316.26],['m16','Ventilationshætte','','stk',32],['m17','Undertagsstrammer','','stk',3.95],['m18','Kingspan vægge/flunker','100 mm','m²',480],['m19','Klemlister til beklædning','','m',4.95],['m20','Forskalling til zink','19x125','stk',20],['m21','Dampspærre','','rulle',699],['m22','Kingspan tape udvendig','','rulle',135],['m23','Dampspærretape','','rulle',186.82],['m24','Tagsten','','stk',17.57],['m25','Endesten','','stk',199],['m26','Rygningssten','','stk',160],['m27','Rendejern','','stk',39],['m28','Fodblik','','stk',29],['m29','Fuglegitter','','stk',17],['m30','Fodplade','21 mm','stk',264]
];
const MATERIALS=mats.map(x=>({id:x[0],name:x[1],dimension:x[2],unit:x[3],price:x[4]}));
const H3ITEMS=[
['Konstruktionstræ','m1',18,'3'],['Konstruktionstræ','m2',32.4,'3.6'],['Konstruktionstræ','m3',12,'3'],['Konstruktionstræ','m4',12,'3'],['Konstruktionstræ','m5',24,'3'],['Konstruktionstræ','m6',20.4,'5.1'],['Konstruktionstræ','m10',4.2,'4.2'],['Konstruktionstræ','m11',24,'3'],['Konstruktionstræ','m19',20.4,'5.1'],['Isolering','m7',7,'1'],['Isolering','m8',14,'1'],['Isolering','m18',6,'1'],['Plader','m9',6,'1'],['Plader','m30',1,'1'],['Undertag','m12',1,'1'],['Undertag','m17',15,'1'],['Brædder / zink','m13',0,''],['Brædder / zink','m14',33.6,'4.2'],['Brædder / zink','m20',28.8,'4.8'],['Vindue','m15',1,'1'],['Tagtilbehør','m16',8,'1'],['Tagtilbehør','m29',5,'1'],['Dampspærre & tape','m21',1,'1'],['Dampspærre & tape','m22',1,'1'],['Dampspærre & tape','m23',1,'1'],['Tagsten','m24',64,'1'],['Tagsten','m25',8,'1'],['Tagsten','m26',8,'1'],['Tagrende & inddækning','m27',6,'1'],['Tagrende & inddækning','m28',5,'1']
];
const KSDATA=[
['Modtagekontrol','Leverance','Leverede varer stemmer med bestilling og følgeseddel'],['Modtagekontrol','Leverance','Materialer kontrolleres for transportskader'],['Modtagekontrol','Konstruktionstræ','Korrekt dimension, kvalitet og fugt på konstruktionstræ'],['Modtagekontrol','Vindue','Vindue kontrolleres for korrekt mål, type og skader'],['Modtagekontrol','Undertag og tæthed','Undertag, dampspærre og tape er de korrekte produkter'],
['Proceskontrol','Forberedelse','Tegninger og tekniske anvisninger er tilgængelige før opstart'],['Proceskontrol','Forberedelse','Nødvendige instruktioner er gennemgået før arbejdet starter'],['Proceskontrol','Kontrolplan','Kritiske knudepunkter til kontrol er fastlagt'],['Proceskontrol','Fotodokumentation','Fotopunkter er valgt før de bygges inde'],['Proceskontrol','Udveksling','Midlertidig understøtning før overskæring af spær'],['Proceskontrol','Udveksling','Udveksling, beslag og fastgørelser er udført efter løsning'],['Proceskontrol','Konstruktion','Stolper, remme og spær er korrekt placeret og i lod/vater'],['Proceskontrol','Lægter','Lægteafstand og fastgørelse kontrolleres'],['Proceskontrol','Undertag','Overlæg, opbuk og samlinger i undertaget er korrekt udført'],['Proceskontrol','Undertag','Overgang mellem eksisterende og nyt undertag er tæt og vandledende'],['Proceskontrol','Vindue','Vindue er opklodset, fastgjort og tætnet korrekt'],['Proceskontrol','Isolering','Isolering har korrekt tykkelse og slutter tæt'],['Proceskontrol','Dampspærre','Dampspærresamlinger og tape er udført lufttæt'],['Proceskontrol','Dampspærre','Ny dampspærre er tilsluttet eksisterende konstruktion lufttæt'],['Proceskontrol','Gennemføringer','Gennemføringer i undertag og dampspærre er tætnet korrekt'],['Proceskontrol','Tagsten','Tagsten, endesten og rygning er korrekt placeret og fastgjort'],['Proceskontrol','Inddækning','Fodblik, zinkunderlag og inddækninger leder vand korrekt væk'],['Proceskontrol','Tagrende','Rendejern og tagrende har korrekt placering og fald'],
['Slutkontrol','Dokumentation','Aftalt KS- og fotodokumentation er komplet'],['Slutkontrol','Udført arbejde','Det færdige arbejde gennemgås for synlige fejl og mangler'],['Slutkontrol','Knudepunkter','Kritiske knudepunkter gennemgås ved aflevering'],['Slutkontrol','Afvigelser','Fejl og mangler registreres med placering og plan for udbedring'],['Slutkontrol','Aflevering','Afvigelser er udbedret og slutresultatet er dokumenteret']
];
const TASKS=[['Tegne / skitsere idéløsning',5,2],['Byggemøde 1 – skitse, detaljer og knudepunkter',0,2],['Tegne projekt / arbejdstegninger',9,2],['Materialeliste og materialeberegning',6,2],['Opsnøring og hovedmål',7,2],['Spær og udveksling',12,2],['Konstruktion – front, flunker og afstivning',13,2],['Kvist – modulopbygning og montage',12,2],['Undertag, skotrende og tagfod',9,2],['Vindue, inddækning og beklædning',7,2],['Isolering, ventilation og dampspærre',6,2],['Byggemøde 2 – kontrol af udførelse',0,2],['KS og fotodokumentation',6,2],['Slutkontrol og udbedring af mangler',3,2],['Forberede fremlæggelse',3,1],['Oprydning',2,2],['Byggemøde 3 – aflevering / evaluering',0,2],['Fremlæggelse',0,1]];
function freshState(){return {settings:{company:'PROJECT',hourlyRate:625,markup:0},activeProjectId:'p4',customers:[{id:'c4',name:'Skoleopgave H3',phone:'',email:'',address:''}],materials:MATERIALS,projects:[{id:'p4',number:'H3-KVIST',name:'Projektopgave kvist H3',customerId:'c4',status:'I gang',start:'2026-08-03',calc:{items:H3ITEMS.map((x,i)=>({id:'i'+i,group:x[0],materialId:x[1],qty:x[2],tradeSize:x[3],waste:0})),labor:[],extras:[{id:'e1',name:'5% befæstigelse (søm og skruer)',qty:1,price:1160.44}]},ks:KSDATA.map((x,i)=>({id:'k'+i,phase:x[0],area:x[1],title:x[2],status:'Ikke startet',photoRequired:i!==4&&i!==5&&i!==6&&i!==7&&i!==8&&i!==23,photos:[],note:'',deviation:''})),hours:[],schedule:{startDate:'2026-08-03',dayHours:7.4,workStart:'07:00',budgetHours:0,tasks:TASKS.map((x,i)=>({id:'t'+i,name:x[0],weight:x[1],crew:x[2],hours:x[1]===0&&x[0].startsWith('Byggemøde')?1:x[0]==='Fremlæggelse'?.25:0}))},presentationNotes:{},presentationImages:{}}]};}
