/* V3 samlet forbedringspakke: kunder på sager, dokumenter, rapporter, arkiv/søgning, materialedatabase, dashboard og Storage */
(function(){
  const BUCKET='project-files';
  const css=`
  .v3-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.v3-toolbar input,.v3-toolbar select{min-height:38px;border:1px solid #d8dee7;border-radius:8px;padding:8px 10px;background:#fff}.v3-search{min-width:240px}.archive-badge{font-size:10px;font-weight:800;background:#eef2f4;color:#64748b;border-radius:999px;padding:6px 9px}.project-card.archived{opacity:.72}.project-card-actions.v3{grid-template-columns:repeat(2,1fr)}
  .doc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:12px}.doc-card{background:#fff;border:1px solid #e6eaee;border-radius:12px;padding:14px;display:grid;gap:9px}.doc-card h3{font-size:13px;margin:0}.doc-card p{font-size:10px;color:#64748b;margin:0}.doc-actions{display:flex;gap:7px;flex-wrap:wrap}.doc-drop{border:2px dashed #cbd5df;border-radius:14px;padding:28px;text-align:center;background:#fbfcfd;margin-bottom:16px}.doc-drop strong{display:block;margin-bottom:5px}.doc-drop small{color:#64748b}.report-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px;margin-top:16px}.report-card{background:#fff;border:1px solid #e6eaee;border-radius:12px;padding:14px}.report-card h3{font-size:13px;margin:0 0 5px}.report-card p{font-size:10px;color:#64748b;min-height:32px}.report-card button{width:100%}
  .material-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.material-toolbar input{min-width:260px;border:1px solid #d8dee7;border-radius:8px;padding:9px 11px}.material-actions{display:flex;gap:6px}.material-link{font-size:10px}.dash-list{display:grid;gap:8px}.dash-item{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid #edf0f2}.dash-item:last-child{border-bottom:0}.dash-item small{display:block;color:#64748b;margin-top:2px}.dash-progress{height:8px;border-radius:999px;background:#edf0f2;overflow:hidden;margin-top:8px}.dash-progress span{display:block;height:100%;background:#397858}.customer-choice{grid-column:1/-1;background:#f7faf8;border:1px solid #dce9e1;border-radius:10px;padding:12px}.customer-choice select{width:100%}.customer-new-note{font-size:10px;color:#64748b;margin-top:5px}.report-print{font-family:Arial,sans-serif;color:#111;padding:28px}.report-print h1{font-size:24px}.report-print h2{font-size:16px;margin-top:24px}.report-print table{width:100%;border-collapse:collapse;margin-top:8px}.report-print th,.report-print td{border-bottom:1px solid #ddd;padding:7px;text-align:left;font-size:12px}.report-print .muted{color:#666}.report-print .total{font-weight:700;font-size:14px}.report-print img{max-width:320px;max-height:220px;object-fit:contain;margin:6px;border:1px solid #ddd}
  @media(max-width:650px){.v3-search,.material-toolbar input{min-width:0;width:100%}.project-card-actions.v3{grid-template-columns:1fr}.doc-grid{grid-template-columns:1fr}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);

  function ensureData(){
    state.customers=state.customers||[];state.materials=state.materials||[];
    (state.projects||[]).forEach(p=>{p.documents=p.documents||[];p.archived=!!p.archived;p.hours=p.hours||[];p.ks=p.ks||[]});
  }
  ensureData();

  function escAttr(s){return h(s??'')}
  function currentCustomer(p){return p?.customerId?state.customers.find(c=>c.id===p.customerId):null}
  function customerAddr(c){return [c?.address,[c?.postalCode,c?.city].filter(Boolean).join(' ')].filter(Boolean).join(', ')}

  /* ----- SAGER: eksisterende kunde + søgning + arkiv ----- */
  const CASE_TYPES_V3=['Tag / kvist','Renovering','Nybyggeri','Tilbygning','Facade','Vinduer / døre','Service / reparation','Forsikringssag','Andet'];
  const CASE_STATUSES_V3=['Tilbud','Planlagt','I gang','Afventer','Afsluttet'];
  function genericKs(type){return [
    ['Modtagekontrol','Materialer',`Kontroller materialer til ${type.toLowerCase()} mod bestilling og for skader`],
    ['Proceskontrol','Opmåling','Kontroller mål, niveauer og eksisterende forhold før opstart'],
    ['Proceskontrol','Udførelse','Kontroller fastgørelser, samlinger og kritiske detaljer under arbejdet'],
    ['Proceskontrol','Fotodokumentation','Tag fotos af kritiske detaljer før de bygges inde'],
    ['Slutkontrol','Udført arbejde','Gennemgå det færdige arbejde for fejl og mangler'],
    ['Slutkontrol','Dokumentation','Kontroller at KS og fotodokumentation er komplet']
  ].map(x=>({id:uid('k'),phase:x[0],area:x[1],title:x[2],status:'Ikke startet',photoRequired:true,photos:[],note:'',deviation:''}))}
  function templateForV3(type){
    if(type==='Tag / kvist'&&typeof KSDATA!=='undefined'){
      const ks=KSDATA.map((x,i)=>({id:uid('k'),phase:x[0],area:x[1],title:x[2],status:'Ikke startet',photoRequired:i!==4&&i!==5&&i!==6&&i!==7&&i!==8&&i!==23,photos:[],note:'',deviation:''}));
      const tasks=(typeof TASKS!=='undefined'?TASKS:[]).map(x=>({id:uid('t'),name:x[0],weight:x[1],crew:x[2],hours:x[1]===0&&x[0].startsWith('Byggemøde')?1:x[0]==='Fremlæggelse'?.25:0,mode:'after'}));
      return {ks,tasks};
    }
    const names=['Opmåling og planlægning','Materialer og bestilling','Klargøring / afdækning',`${type} – udførelse`,'KS og fotodokumentation','Oprydning og slutkontrol'];
    return {ks:genericKs(type),tasks:names.map((name,i)=>({id:uid('t'),name,weight:[10,5,10,55,10,10][i],crew:2,hours:0,mode:'after'}))};
  }

  window.openProjectForm=function(projectId=''){
    ensureData();const editing=!!projectId,p=editing?state.projects.find(x=>x.id===projectId):null,c=currentCustomer(p),root=document.getElementById('modal-root');if(!root)return;
    const selected=p?.customerId||'';
    root.innerHTML=`<div class="case-modal" onclick="if(event.target===this)closeProjectForm()"><form class="case-form" onsubmit="saveProjectFormV3(event,'${projectId}')">
      <div class="case-form-head"><div><small>${editing?'REDIGER SAG':'NY SAG'}</small><h2>${editing?'Sagsoplysninger':'Opret ny sag'}</h2><p>Vælg en gemt kunde eller skriv en ny, og udfyld oplysninger om sagen.</p></div><button type="button" class="case-close" onclick="closeProjectForm()">×</button></div>
      <div class="case-form-body">
        <section><h3>Kunde</h3><div class="case-grid two"><label class="customer-choice">Vælg eksisterende kunde<select id="case-customer-select" onchange="fillCustomerV3(this.value)"><option value="">+ Ny kunde / skriv selv</option>${state.customers.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${h(x.name)}</option>`).join('')}</select><span class="customer-new-note">Når du vælger en kunde, udfyldes kontakt og adresse automatisk.</span></label>
        <label>Kunde / virksomhed<input id="case-customer" value="${escAttr(c?.name||p?.customerName)}"></label><label>Kontaktperson<input id="case-contact" value="${escAttr(p?.contactName||c?.contact)}"></label><label>Telefon<input id="case-phone" type="tel" value="${escAttr(p?.phone||c?.phone)}"></label><label>E-mail<input id="case-email" type="email" value="${escAttr(p?.email||c?.email)}"></label></div></section>
        <section><h3>Sagen</h3><div class="case-grid two"><label>Sagsnavn *<input id="case-name" required value="${escAttr(p?.name)}" placeholder="Fx Kvist – Søndergade 12"></label><label>Sagsnummer<input id="case-number" value="${escAttr(p?.number||(typeof nextCaseNumber==='function'?nextCaseNumber():'NY-SAG'))}"></label><label>Sagstype<select id="case-type">${CASE_TYPES_V3.map(x=>`<option ${x===(p?.caseType||'Tag / kvist')?'selected':''}>${x}</option>`).join('')}</select></label><label>Status<select id="case-status">${CASE_STATUSES_V3.map(x=>`<option ${x===(p?.status||'Tilbud')?'selected':''}>${x}</option>`).join('')}</select></label><label>Startdato<input id="case-start" type="date" value="${escAttr(p?.start||new Date().toISOString().slice(0,10))}"></label><label>Kort beskrivelse<input id="case-description" value="${escAttr(p?.description)}"></label></div></section>
        <section><h3>Adresse</h3><div class="case-grid address"><label class="wide">Adresse<input id="case-address" value="${escAttr(p?.address||c?.address)}"></label><label>Postnr.<input id="case-postal" value="${escAttr(p?.postalCode||c?.postalCode)}"></label><label>By<input id="case-city" value="${escAttr(p?.city||c?.city)}"></label></div></section>
      </div><div class="case-form-actions"><button type="button" class="secondary" onclick="closeProjectForm()">Annuller</button><button class="primary" type="submit">${editing?'Gem ændringer':'Opret sag'}</button></div></form></div>`;
  };
  window.fillCustomerV3=function(id){const c=state.customers.find(x=>x.id===id);if(!c)return;[['case-customer',c.name],['case-contact',c.contact],['case-phone',c.phone],['case-email',c.email],['case-address',c.address],['case-postal',c.postalCode],['case-city',c.city]].forEach(([i,v])=>{const e=document.getElementById(i);if(e)e.value=v||''})};
  window.saveProjectFormV3=function(e,projectId=''){
    e.preventDefault();const val=id=>document.getElementById(id)?.value.trim()||'',name=val('case-name');if(!name)return toast('Skriv et sagsnavn');
    let customerId=val('case-customer-select'),customer=customerId?state.customers.find(c=>c.id===customerId):null;
    if(!customer&&val('case-customer')){customer={id:uid('c'),name:val('case-customer'),contact:val('case-contact'),phone:val('case-phone'),email:val('case-email'),address:val('case-address'),postalCode:val('case-postal'),city:val('case-city'),notes:''};state.customers.push(customer);customerId=customer.id}
    const common={number:val('case-number')||'NY-SAG',name,status:val('case-status')||'Tilbud',caseType:val('case-type')||'Andet',start:val('case-start'),description:val('case-description'),address:val('case-address'),postalCode:val('case-postal'),city:val('case-city'),customerName:val('case-customer'),contactName:val('case-contact'),phone:val('case-phone'),email:val('case-email'),customerId};
    let p=projectId?state.projects.find(x=>x.id===projectId):null;
    if(p)Object.assign(p,common);else{const tpl=templateForV3(common.caseType);p={id:uid('p'),...common,archived:false,documents:[],calc:{items:[],labor:[],extras:[]},ks:tpl.ks,hours:[],schedule:{startDate:common.start||new Date().toISOString().slice(0,10),dayHours:7.4,workStart:'07:00',budgetHours:0,tasks:tpl.tasks},presentationNotes:{},presentationImages:{}};state.projects.push(p);state.activeProjectId=p.id}
    saveState();closeProjectForm();renderAll();go('projects');toast(projectId?'Sag opdateret':'Sag oprettet');
  };
  window.toggleArchiveProject=function(id){const p=state.projects.find(x=>x.id===id);if(!p)return;p.archived=!p.archived;saveState();renderProjects();toast(p.archived?'Sag arkiveret':'Sag gendannet')};
  window.renderProjects=function(){ensureData();const page=document.getElementById('projects-page');if(!page)return;const q=(window._caseSearch||'').toLowerCase(),filter=window._caseFilter||'active';let arr=state.projects.filter(p=>filter==='all'||(filter==='archived'?p.archived:!p.archived));if(q)arr=arr.filter(p=>[p.name,p.number,p.caseType,p.customerName,p.city,p.address].join(' ').toLowerCase().includes(q));page.innerHTML=`<div class="pagehead"><div><h1>Sager</h1><p>Søg, arkivér og administrer alle sager.</p></div><button class="primary" onclick="openProjectForm()">+ Ny sag</button></div><div class="v3-toolbar" style="margin-bottom:14px"><input class="v3-search" placeholder="Søg i sager…" value="${h(window._caseSearch||'')}" oninput="window._caseSearch=this.value;renderProjects()"><select onchange="window._caseFilter=this.value;renderProjects()"><option value="active" ${filter==='active'?'selected':''}>Aktive sager</option><option value="archived" ${filter==='archived'?'selected':''}>Arkiv</option><option value="all" ${filter==='all'?'selected':''}>Alle</option></select></div><div class="project-grid">${arr.map(p=>{const t=totals(p),c=currentCustomer(p),addr=[p.address,[p.postalCode,p.city].filter(Boolean).join(' ')].filter(Boolean).join(', ');return`<article class="project-card project-card-rich ${p.archived?'archived':''}"><div class="project-card-top"><span class="status ${statusClass(p.status)}">${h(p.status)}</span>${p.archived?'<span class="archive-badge">Arkiveret</span>':`<span class="case-type-badge">${h(p.caseType||'Ikke angivet')}</span>`}</div><h3>${h(p.name)}</h3><p class="case-number">${h(p.number)}</p>${addr?`<div class="case-info"><span>⌖</span><div><small>Adresse</small><b>${h(addr)}</b></div></div>`:''}${c||p.customerName?`<div class="case-info"><span>♙</span><div><small>Kunde</small><b>${h(c?.name||p.customerName)}</b></div></div>`:''}<div class="cardline"><span>Materialer</span><b>${kr(t.materials)}</b></div><div class="cardline"><span>KS</span><b>${ksStats(p).ok}/${ksStats(p).total}</b></div><div class="project-card-actions v3"><button class="secondary" onclick="openProjectForm('${p.id}')">Rediger</button><button class="secondary" onclick="state.activeProjectId='${p.id}';saveState(false);renderAll();go('dashboard')">Gør aktiv</button><button class="secondary" onclick="toggleArchiveProject('${p.id}')">${p.archived?'Gendan':'Arkivér'}</button><button class="dangerbtn" onclick="deleteProject('${p.id}')">Slet sag</button></div></article>`}).join('')}</div>`};

  /* ----- DOKUMENTER + SUPABASE STORAGE ----- */
  pageMap.documents='documents-page';
  const oldRenderPage=renderPage;
  renderPage=function(p){if(p==='documents')return renderDocuments();return oldRenderPage(p)};
  window.renderPage=renderPage;
  window.uploadProjectDocument=async function(input){ensureData();const f=input.files?.[0];if(!f)return;if(!sb||!cloudUser)return toast('Log ind for at uploade dokumenter');const p=active(),safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${cloudUser.id}/${p.id}/documents/${Date.now()}_${safe}`;toast('Uploader dokument…');const {error}=await sb.storage.from(BUCKET).upload(path,f,{upsert:false,contentType:f.type||undefined});if(error){console.error(error);return toast('Upload fejlede')};p.documents.push({id:uid('d'),name:f.name,path,type:f.type||'',size:f.size,createdAt:new Date().toISOString()});saveState();renderDocuments();toast('Dokument gemt')};
  window.openProjectDocument=async function(id){const d=active().documents.find(x=>x.id===id);if(!d)return;if(d.dataUrl)return window.open(d.dataUrl,'_blank');if(!sb||!cloudUser)return toast('Log ind for at åbne dokumentet');const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(d.path,300);if(error)return toast('Kunne ikke åbne dokument');window.open(data.signedUrl,'_blank')};
  window.deleteProjectDocument=async function(id){const p=active(),d=p.documents.find(x=>x.id===id);if(!d)return;if(!confirm(`Slet “${d.name}”?`))return;if(d.path&&sb&&cloudUser)await sb.storage.from(BUCKET).remove([d.path]);p.documents=p.documents.filter(x=>x.id!==id);saveState();renderDocuments();toast('Dokument slettet')};
  window.renderDocuments=function(){ensureData();const p=active(),page=document.getElementById('documents-page');if(!page)return;page.innerHTML=`<div class="pagehead"><div><h1>Dokumenter</h1><p>Arbejdstegninger, tilbud, montagevejledninger, billeder og øvrige sagsfiler.</p></div></div><label class="doc-drop"><strong>+ Upload dokument</strong><small>PDF, billeder, regneark og andre sagsfiler · maks. 25 MB</small><input type="file" hidden onchange="uploadProjectDocument(this)"></label>${p.documents.length?`<div class="doc-grid">${p.documents.map(d=>`<article class="doc-card"><div><h3>${h(d.name)}</h3><p>${h(d.type||'Fil')} · ${Math.max(1,Math.round((d.size||0)/1024))} KB</p></div><div class="doc-actions"><button class="secondary" onclick="openProjectDocument('${d.id}')">Åbn</button><button class="dangerbtn" onclick="deleteProjectDocument('${d.id}')">Slet</button></div></article>`).join('')}</div>`:'<div class="card" style="padding:22px;text-align:center">Ingen dokumenter på sagen endnu.</div>'}<div class="report-grid"><article class="report-card"><h3>KS-rapport</h3><p>Status, kommentarer og kontrolpunkter.</p><button class="secondary" onclick="printReportV3('ks')">Udskriv / PDF</button></article><article class="report-card"><h3>Timeregnskab</h3><p>Registrerede timer fordelt på opgaver.</p><button class="secondary" onclick="printReportV3('hours')">Udskriv / PDF</button></article><article class="report-card"><h3>Kalkulation</h3><p>Materialer, arbejdsløn og samlet økonomi.</p><button class="secondary" onclick="printReportV3('calc')">Udskriv / PDF</button></article><article class="report-card"><h3>Samlet sagsrapport</h3><p>Sagsdata, økonomi, timer og KS i én rapport.</p><button class="primary" onclick="printReportV3('full')">Udskriv / PDF</button></article></div>`};

  /* Nye KS-fotos til Storage; gamle base64-billeder understøttes fortsat. */
  window.ksPhoto=function(i){const inp=document.getElementById('ks-file');if(!inp)return;inp.onchange=async()=>{const f=inp.files?.[0];if(!f)return;const k=active().ks[i];k.photos=k.photos||[];if(sb&&cloudUser){const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${cloudUser.id}/${active().id}/ks/${k.id}/${Date.now()}_${safe}`;toast('Uploader foto…');const {error}=await sb.storage.from(BUCKET).upload(path,f,{contentType:f.type||'image/jpeg'});if(error){console.error(error);return toast('Foto-upload fejlede')};k.photos.push({path,name:f.name,type:f.type,size:f.size})}else{const r=new FileReader();await new Promise(res=>{r.onload=()=>{k.photos.push(r.result);res()};r.readAsDataURL(f)})}if(k.status==='Mangler foto'||k.status==='Ikke startet')k.status='Godkendt';saveState();renderKs();renderTop();toast('Foto gemt')};inp.click()};
  window.renderKsViewer=async function(){const k=active().ks?.[ksViewerIndex];if(!k?.photos?.length)return closeKsViewer();ksViewerPhotoIndex=Math.max(0,Math.min(ksViewerPhotoIndex,k.photos.length-1));const item=k.photos[ksViewerPhotoIndex];let src=typeof item==='string'?item:item?.dataUrl||'';if(!src&&item?.path&&sb&&cloudUser){const {data}=await sb.storage.from(BUCKET).createSignedUrl(item.path,300);src=data?.signedUrl||''}document.getElementById('modal-root').innerHTML=`<div class="photo-viewer" id="ks-photo-viewer" onclick="if(event.target===this)closeKsViewer()"><div class="photo-viewer-card"><button class="photo-close" onclick="closeKsViewer()">×</button><div class="photo-viewer-head"><div><small>${h(k.phase)} · ${h(k.area)}</small><h3>${h(k.title)}</h3></div><span>${ksViewerPhotoIndex+1} / ${k.photos.length}</span></div><div class="photo-stage">${src?`<img src="${src}" alt="KS dokumentationsfoto">`:'<span style="color:#fff">Billedet kunne ikke indlæses</span>'}</div><div class="photo-controls"><button class="secondary" ${ksViewerPhotoIndex===0?'disabled':''} onclick="stepKsPhoto(-1)">← Forrige</button><button class="dangerbtn" onclick="deleteKsPhotoV3()">Slet billede</button><button class="secondary" ${ksViewerPhotoIndex===k.photos.length-1?'disabled':''} onclick="stepKsPhoto(1)">Næste →</button></div></div></div>`};
  window.deleteKsPhotoV3=async function(){const k=active().ks?.[ksViewerIndex],item=k?.photos?.[ksViewerPhotoIndex];if(!item||!confirm('Vil du slette dette billede?'))return;if(typeof item==='object'&&item.path&&sb&&cloudUser)await sb.storage.from(BUCKET).remove([item.path]);k.photos.splice(ksViewerPhotoIndex,1);saveState();renderKs();if(k.photos.length){ksViewerPhotoIndex=Math.min(ksViewerPhotoIndex,k.photos.length-1);renderKsViewer()}else closeKsViewer()};

  /* ----- RAPPORTER ----- */
  function reportHead(p){const c=currentCustomer(p),addr=[p.address,[p.postalCode,p.city].filter(Boolean).join(' ')].filter(Boolean).join(', ');return `<h1>${h(p.name)}</h1><div class="muted">${h(p.number)} · ${h(p.caseType||'Sag')}</div>${c||p.customerName?`<p><b>Kunde:</b> ${h(c?.name||p.customerName)}<br>${h(addr)}</p>`:''}`}
  function calcReport(p){const t=totals(p);return `<h2>Kalkulation</h2><table><tr><th>Materiale</th><th>Mængde</th><th>Pris</th><th>I alt</th></tr>${(p.calc.items||[]).map(i=>{const m=mat(i.materialId),sum=Number(i.qty||0)*(1+Number(i.waste||0)/100)*Number(m.price||0);return`<tr><td>${h(m.name)}</td><td>${num(i.qty)} ${h(m.unit)}</td><td>${kr(m.price)}</td><td>${kr(sum)}</td></tr>`}).join('')}</table><p class="total">Materialer: ${kr(t.materials)} · Arbejdsløn: ${kr(t.labor)} · Øvrigt: ${kr(t.extras)} · Samlet: ${kr(t.total)}</p>`}
  function hoursReport(p){const sum=(p.hours||[]).reduce((a,x)=>a+Number(x.hours||0),0);return `<h2>Timeregnskab</h2><table><tr><th>Dato</th><th>Person</th><th>Opgave</th><th>Timer</th><th>Note</th></tr>${(p.hours||[]).map(x=>`<tr><td>${h(x.date)}</td><td>${h(x.person)}</td><td>${h(x.task)}</td><td>${num(x.hours,2)}</td><td>${h(x.note||'')}</td></tr>`).join('')}</table><p class="total">I alt: ${num(sum,2)} timer</p>`}
  function ksReport(p){return `<h2>KS & dokumentation</h2><table><tr><th>Fase</th><th>Kontrolpunkt</th><th>Status</th><th>Kommentar</th><th>Fotos</th></tr>${(p.ks||[]).map(k=>`<tr><td>${h(k.phase)}</td><td><b>${h(k.title)}</b><br><span class="muted">${h(k.area)}</span></td><td>${h(k.status)}</td><td>${h(k.note||k.comment||'')}</td><td>${k.photos?.length||0}</td></tr>`).join('')}</table>`}
  window.printReportV3=function(kind){const p=active();let body=reportHead(p);if(kind==='calc'||kind==='full')body+=calcReport(p);if(kind==='hours'||kind==='full')body+=hoursReport(p);if(kind==='ks'||kind==='full')body+=ksReport(p);if(kind==='full')body+=`<h2>Dokumenter</h2><p>${p.documents?.length||0} dokument(er) gemt på sagen.</p>`;const w=window.open('','_blank');if(!w)return toast('Browseren blokerede rapportvinduet');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${h(p.number)} rapport</title><style>${css}.report-print{max-width:1000px;margin:auto}@media print{button{display:none}}</style></head><body><div class="report-print">${body}<p class="muted">Genereret ${new Date().toLocaleString('da-DK')}</p><button onclick="window.print()">Udskriv / Gem som PDF</button></div></body></html>`);w.document.close()};

  /* ----- MATERIALER: CRUD + søgning ----- */
  window.renderMaterials=function(){ensureData();const q=(window._matSearch||'').toLowerCase(),arr=state.materials.filter(m=>[m.name,m.dimension,m.unit,m.supplier,m.sku].join(' ').toLowerCase().includes(q));document.getElementById('materials-page').innerHTML=`<div class="pagehead"><div><h1>Materialer</h1><p>Redigerbar materialedatabase til alle sager.</p></div><button class="primary" onclick="openMaterialFormV3()">+ Nyt materiale</button></div><div class="material-toolbar"><input placeholder="Søg materiale, varenr. eller leverandør…" value="${h(window._matSearch||'')}" oninput="window._matSearch=this.value;renderMaterials()"></div><div class="tablewrap"><table><thead><tr><th>Materiale</th><th>Dimension</th><th>Enhed</th><th>Pris inkl. moms</th><th>Leverandør</th><th>Varenr.</th><th></th></tr></thead><tbody>${arr.map(m=>`<tr><td>${h(m.name)}</td><td>${h(m.dimension||'')}</td><td>${h(m.unit||'')}</td><td>${kr(m.price)}</td><td>${h(m.supplier||'')}</td><td>${h(m.sku||'')}</td><td><div class="material-actions"><button class="mini-btn" onclick="openMaterialFormV3('${m.id}')">Rediger</button><button class="mini-btn" onclick="deleteMaterialV3('${m.id}')">Slet</button></div></td></tr>`).join('')}</tbody></table></div>`};
  window.openMaterialFormV3=function(id=''){const m=id?state.materials.find(x=>x.id===id):null,root=document.getElementById('modal-root');root.innerHTML=`<div class="case-modal" onclick="if(event.target===this)closeProjectForm()"><form class="case-form" onsubmit="saveMaterialV3(event,'${id}')"><div class="case-form-head"><div><small>${id?'REDIGER':'NYT'} MATERIALE</small><h2>${id?'Rediger materiale':'Opret materiale'}</h2></div><button type="button" class="case-close" onclick="closeProjectForm()">×</button></div><div class="case-form-body"><div class="case-grid two"><label>Navn *<input id="mat-name" required value="${escAttr(m?.name)}"></label><label>Dimension<input id="mat-dim" value="${escAttr(m?.dimension)}"></label><label>Enhed<input id="mat-unit" value="${escAttr(m?.unit)}" placeholder="m, stk, m²…"></label><label>Pris inkl. moms<input id="mat-price" type="number" step="0.01" value="${m?.price||0}"></label><label>Leverandør<input id="mat-supplier" value="${escAttr(m?.supplier)}"></label><label>Varenummer<input id="mat-sku" value="${escAttr(m?.sku)}"></label><label style="grid-column:1/-1">Produktlink<input id="mat-link" value="${escAttr(m?.link)}"></label></div></div><div class="case-form-actions"><button type="button" class="secondary" onclick="closeProjectForm()">Annuller</button><button class="primary">Gem materiale</button></div></form></div>`};
  window.saveMaterialV3=function(e,id=''){e.preventDefault();const v=x=>document.getElementById(x)?.value.trim()||'',data={name:v('mat-name'),dimension:v('mat-dim'),unit:v('mat-unit'),price:Number(v('mat-price')||0),supplier:v('mat-supplier'),sku:v('mat-sku'),link:v('mat-link')};if(!data.name)return toast('Skriv materialets navn');const m=id?state.materials.find(x=>x.id===id):null;if(m)Object.assign(m,data);else state.materials.push({id:uid('m'),...data});saveState();closeProjectForm();renderMaterials();toast('Materiale gemt')};
  window.deleteMaterialV3=function(id){const used=(state.projects||[]).some(p=>(p.calc.items||[]).some(i=>i.materialId===id));if(used)return toast('Materialet bruges på en sag og kan ikke slettes');if(!confirm('Slet materialet?'))return;state.materials=state.materials.filter(x=>x.id!==id);saveState();renderMaterials()};

  /* ----- DASHBOARD ----- */
  window.renderDashboard=function(){ensureData();const p=active(),t=totals(p),s=ksStats(p),hrs=p.hours||[],hours=hrs.reduce((a,x)=>a+Number(x.hours||0),0),planned=(p.schedule?.tasks||[]).reduce((a,x)=>a+Number(x.hours||0),0),pct=planned?Math.min(100,Math.round(hours/planned*100)):0,recent=[...hrs].slice(-4).reverse(),missing=(p.ks||[]).filter(k=>k.status!=='Godkendt').slice(0,5);document.getElementById('dashboard-page').innerHTML=`<div class="pagehead"><div><h1>${h(p.name)}</h1><p>${h(p.number)} · ${h(p.caseType||'projektstyring')}</p></div><div class="v3-toolbar"><button class="secondary" onclick="go('documents')">Dokumenter & rapporter</button><button class="primary" onclick="go('presentation')">▶ Fremlæggelse</button></div></div><div class="metrics"><article class="card metric"><span>Materialer inkl. moms</span><strong>${kr(t.materials)}</strong></article><article class="card metric"><span>Projektudgifter</span><strong>${kr(t.total)}</strong></article><article class="card metric"><span>Registrerede timer</span><strong>${num(hours,2)} t.</strong><small>${planned?`${num(planned,2)} t. planlagt`:''}</small></article><article class="card metric"><span>KS</span><strong>${s.ok}/${s.total}</strong><small>${s.pending+s.photo+s.error} mangler</small></article></div><div class="grid2"><section class="panel"><div class="panelhead"><div><h2>Timer mod plan</h2><p>Faktisk registreret sammenholdt med tidsplanen.</p></div><b>${planned?pct+'%':'—'}</b></div><div class="dash-progress"><span style="width:${pct}%"></span></div><div class="dash-list" style="margin-top:12px">${recent.length?recent.map(x=>`<div class="dash-item"><div><b>${h(x.task||'Opgave')}</b><small>${h(x.date)} · ${h(x.person||'')}</small></div><strong>${num(x.hours,2)} t.</strong></div>`).join(''):'<small>Ingen timer registreret endnu.</small>'}</div></section><section class="panel"><div class="panelhead"><div><h2>KS der kræver opmærksomhed</h2><p>Næste kontrolpunkter.</p></div></div><div class="dash-list">${missing.length?missing.map(k=>`<div class="dash-item"><div><b>${h(k.title)}</b><small>${h(k.phase)} · ${h(k.area)}</small></div><span class="status ${k.status==='Fejl/mangel'?'done':'wait'}">${h(k.status)}</span></div>`).join(''):'<small>Alle KS-punkter er godkendt.</small>'}</div></section></div>`};

  /* Sørg for dokument-navigation på knapper der tilføjes efter app.js. */
  setTimeout(()=>{document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));renderAll()},50);
})();
