/* V4 H3-opgavepakke: opgavekrav, tegninger, teknisk dokumentation, ansvar og fælles filmetadata */
(function(){
  const BUCKET='project-files';
  const META_TABLE='project_files';
  const REQUIREMENTS=[
    {key:'loft_til_kip',title:'Loft til kip',detail:'Kvisten skal udføres med loft til kip.',measure:'Kontrol / mål'},
    {key:'flunk_80',title:'Flunkhøjde 80 cm',detail:'Højden på flunken målt ved front skal være 80 cm.',measure:'Målt højde'},
    {key:'front_140',title:'Frontbredde 140 cm',detail:'Frontens konstruktionsbredde skal være 140 cm.',measure:'Målt bredde'},
    {key:'stern_vinkelret',title:'Vinkelret afskåret stern',detail:'Der skal udføres vinkelret afskåret stern.',measure:'Kontrol'},
    {key:'skotrende_bund',title:'Løsning ved bunden af skotrenden',detail:'Der skal udføres og dokumenteres en løsning ved bunden af skotrenden.',measure:'Kontrol / detalje'},
    {key:'flunk_tag_overgang',title:'Overgang mellem flunk og tagflade',detail:'Overgangen mellem flunk og tagflade skal udføres og dokumenteres.',measure:'Kontrol / detalje'},
    {key:'hjorne_beklaedning',title:'Beklædning 30–40 cm rundt om hjørnet',detail:'Beklædning skal føres 30–40 cm hen langs både front og flunk.',measure:'Målt længde'},
    {key:'vindue_600',title:'Vindueshul 600 × 600 mm',detail:'Der skal udføres vindueshul med karmmål 600 × 600 mm og beklædningsløsninger omkring.',measure:'Karmmål'},
    {key:'indvendig_1m2',title:'Min. 1 m² indvendig beklædning',detail:'Der skal udføres indvendig beklædning mellem skråvæg og kvist på mindst 1 m².',measure:'Målt areal'}
  ];
  const REQ_STATUSES=['Ikke startet','I gang','Opfyldt','Afvigelse'];
  const DRAWING_TYPES=['Skitse / frihånd','Projekttegning','Arbejdstegning','Detaljetegning'];
  const DRAWING_STATUSES=['Kladde','Til godkendelse','Godkendt'];
  const TECH_FIELDS={
    buildingType:'Bygningstype',existingRoof:'Eksisterende tag / konstruktion',roofPitch:'Taghældning',roofMaterial:'Tagbeklædning',insulationSolution:'Isoleringsopbygning',uValue:'U-værdi / energidokumentation',brDocumentation:'BR / krav og dokumentation',undertagReason:'Valg og begrundelse – undertag',roofCoveringReason:'Valg og begrundelse – tagbeklædning',insulationReason:'Valg og begrundelse – isoleringsmateriale',strength:'Styrke, fastgørelse og afstivning',moisture:'Fugt og vandførende detaljer',energy:'Energi og kuldebroer',ventilationTightness:'Ventilation, dampspærre og tæthed',alternatives:'Alternative løsninger og konsekvenser'};

  const style=document.createElement('style');
  style.textContent=`
  .h3-progress{display:flex;align-items:center;gap:10px;min-width:210px}.h3-progressbar{height:8px;background:#e8edf0;border-radius:999px;overflow:hidden;flex:1}.h3-progressbar span{display:block;height:100%;background:#397858}.h3-requirements{display:grid;gap:10px}.h3-req{background:#fff;border:1px solid #e5e9ed;border-radius:12px;padding:14px;display:grid;grid-template-columns:28px minmax(220px,1.6fr) 150px minmax(160px,.8fr) minmax(210px,1fr);gap:10px;align-items:start}.h3-req.done{border-left:4px solid #397858}.h3-req.warn{border-left:4px solid #b66a2d}.h3-req-index{width:26px;height:26px;border-radius:50%;display:grid;place-items:center;background:#eef2f4;font-size:10px;font-weight:900}.h3-req-title b{display:block;font-size:12px}.h3-req-title small{display:block;color:#64748b;line-height:1.4;margin-top:4px}.h3-req select,.h3-req input,.h3-req textarea,.tech-form input,.tech-form textarea,.drawing-toolbar select{width:100%;border:1px solid #d7dee5;border-radius:8px;padding:9px 10px;background:#fff;font:inherit}.h3-req textarea{min-height:62px;resize:vertical}.h3-req label,.tech-field label{display:block;font-size:9px;font-weight:800;color:#64748b;margin-bottom:4px;text-transform:uppercase;letter-spacing:.45px}.req-photo-list{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.req-photo-list button{font-size:9px;padding:5px 7px}.h3-intro{background:#f6faf7;border:1px solid #dce9e1;border-radius:12px;padding:13px;margin-bottom:14px;font-size:11px;line-height:1.5;color:#475569}
  .drawing-toolbar{display:flex;gap:8px;align-items:end;flex-wrap:wrap;margin-bottom:14px}.drawing-toolbar label{font-size:10px;font-weight:800;color:#64748b;display:grid;gap:5px}.drawing-toolbar select{min-width:170px}.drawing-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px}.drawing-card{background:#fff;border:1px solid #e5e9ed;border-radius:12px;padding:14px;display:grid;gap:10px}.drawing-card-top{display:flex;justify-content:space-between;gap:8px}.drawing-card h3{font-size:13px;margin:0;overflow-wrap:anywhere}.drawing-card small{color:#64748b}.drawing-status{font-size:9px;font-weight:900;border-radius:999px;padding:5px 8px;background:#eef2f4;white-space:nowrap}.drawing-status.approved{background:#e9f5ee;color:#397858}.drawing-actions{display:flex;gap:7px;flex-wrap:wrap}.drawing-card select{border:1px solid #d7dee5;border-radius:8px;padding:8px;background:#fff;font-size:10px}
  .tech-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.tech-card{background:#fff;border:1px solid #e5e9ed;border-radius:12px;padding:16px}.tech-card h2{font-size:14px;margin:0 0 4px}.tech-card>p{font-size:10px;color:#64748b;margin:0 0 14px}.tech-form{display:grid;gap:11px}.tech-form textarea{min-height:95px;resize:vertical}.tech-actions{display:flex;justify-content:flex-end;margin-top:12px}.tech-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:14px}.tech-summary>div{background:#fff;border:1px solid #e5e9ed;border-radius:10px;padding:11px}.tech-summary span{display:block;font-size:9px;color:#64748b}.tech-summary b{display:block;margin-top:3px;font-size:12px}
  .team-settings{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin:0 0 12px}.team-settings label{display:grid;gap:4px;font-size:9px;font-weight:800;color:#64748b}.team-settings input{border:1px solid #d7dee5;border-radius:8px;padding:8px 10px;min-width:150px}.schedule-row.v4{grid-template-columns:minmax(190px,2fr) 60px 85px 65px 115px 90px 85px 135px 135px 32px;min-width:1080px}.schedule-row.v4 select{width:100%;border:1px solid #d7dee5;border-radius:6px;padding:6px;background:#fff;font-size:10px}
  .presentation-source-panel{background:#f7faf8;border:1px solid #dce9e1;border-radius:12px;padding:13px;margin-bottom:14px}.presentation-source-panel>div:first-child{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:9px}.presentation-source-panel h3{font-size:12px;margin:0}.presentation-source-panel p{font-size:10px;color:#64748b;margin:2px 0 0}.source-chips{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.source-chip{border:1px solid #dfe7e2;background:#fff;border-radius:9px;padding:9px;text-align:left;cursor:pointer}.source-chip span{display:block;font-size:9px;color:#64748b}.source-chip b{display:block;font-size:12px;margin-top:2px}.shared-owner{font-size:9px;color:#64748b}.shared-note{font-size:10px;color:#64748b;margin-top:8px}
  @media(max-width:900px){.h3-req{grid-template-columns:28px 1fr 150px}.h3-req .req-measure,.h3-req .req-comment{grid-column:2/-1}.tech-grid{grid-template-columns:1fr}.tech-summary,.source-chips{grid-template-columns:1fr 1fr}}
  @media(max-width:650px){.h3-req{grid-template-columns:28px 1fr}.h3-req>*:not(.h3-req-index){grid-column:2}.tech-summary,.source-chips{grid-template-columns:1fr}.drawing-toolbar>*{width:100%}.drawing-toolbar select{width:100%}.drawing-grid{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);

  function isH3(p){return /H3|KVIST/i.test(`${p?.number||''} ${p?.name||''}`)||p?.caseType==='Tag / kvist'}
  function ensureV4(p=active()){
    if(!p)return;
    p.drawings=p.drawings||[];
    p.technical=p.technical||{};
    p.teamMembers=p.teamMembers||['Person 1','Person 2'];
    if(p.teamMembers.length<2)p.teamMembers=[p.teamMembers[0]||'Person 1','Person 2'];
    if(isH3(p)){
      p.assignmentRequirements=p.assignmentRequirements||[];
      REQUIREMENTS.forEach(r=>{if(!p.assignmentRequirements.some(x=>x.key===r.key))p.assignmentRequirements.push({key:r.key,status:'Ikke startet',measure:'',comment:''})});
    }
    (p.schedule?.tasks||[]).forEach(t=>{if(!t.responsible)t.responsible='both'});
  }
  (state.projects||[]).forEach(ensureV4);

  async function fetchMeta(category){
    if(!sb||!cloudUser)return [];
    const {data,error}=await sb.from(META_TABLE).select('*').eq('project_ref',active().id).eq('category',category).order('created_at',{ascending:false});
    if(error){console.error(error);return []}
    return data||[];
  }
  async function uploadShared(file,category,extra={}){
    if(!file)return null;if(!sb||!cloudUser){toast('Log ind for at uploade filer');return null}
    const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');
    const path=`${cloudUser.id}/${active().id}/${category}/${Date.now()}_${safe}`;
    const {error:upErr}=await sb.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type||undefined});
    if(upErr){console.error(upErr);toast('Upload fejlede');return null}
    const row={project_ref:active().id,category,name:file.name,path,mime_type:file.type||'',size_bytes:file.size||0,uploaded_by:cloudUser.id,...extra};
    const {data,error}=await sb.from(META_TABLE).insert(row).select().single();
    if(error){console.error(error);await sb.storage.from(BUCKET).remove([path]);toast('Filen blev ikke registreret');return null}
    return data;
  }
  async function openShared(row){
    if(!row?.path||!sb||!cloudUser)return toast('Filen kan ikke åbnes');
    const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(row.path,600);
    if(error||!data?.signedUrl)return toast('Kunne ikke åbne filen');
    window.open(data.signedUrl,'_blank');
  }
  async function deleteShared(row){
    if(!row||!cloudUser)return false;
    if(row.uploaded_by!==cloudUser.id){toast('Kun den bruger der uploadede filen kan slette den');return false}
    if(!confirm(`Slet “${row.name}”?`))return false;
    const {error:storageError}=await sb.storage.from(BUCKET).remove([row.path]);
    if(storageError){console.error(storageError);toast('Kunne ikke slette filen');return false}
    const {error}=await sb.from(META_TABLE).delete().eq('id',row.id);
    if(error){console.error(error);toast('Filmetadata kunne ikke slettes');return false}
    return true;
  }
  window.openSharedFileV4=async id=>{const groups=['documents','drawings','requirement'];let row=null;for(const g of groups){row=(window._v4MetaCache?.[g]||[]).find(x=>x.id===id);if(row)break}if(!row&&sb){const {data}=await sb.from(META_TABLE).select('*').eq('id',id).maybeSingle();row=data}if(row)openShared(row)};

  /* ----- OPGAVEKRAV ----- */
  pageMap.requirements='requirements-page';
  window.reqSetV4=function(index,key,value){const p=active();ensureV4(p);p.assignmentRequirements[index][key]=value;saveState(false);if(key==='status')renderRequirementsV4()};
  window.uploadRequirementPhotoV4=async function(index,input){const p=active();ensureV4(p);const req=p.assignmentRequirements[index],file=input.files?.[0];if(!file)return;toast('Uploader dokumentation…');const row=await uploadShared(file,'requirement',{requirement_key:req.key});if(row){toast('Foto gemt');renderRequirementsV4()}};
  window.deleteRequirementPhotoV4=async function(id){const row=(window._v4MetaCache?.requirement||[]).find(x=>x.id===id);if(await deleteShared(row))renderRequirementsV4()};
  window.renderRequirementsV4=async function(){
    const p=active();ensureV4(p);const page=document.getElementById('requirements-page');if(!page)return;
    if(!isH3(p)){page.innerHTML=`<div class="pagehead"><div><h1>Opgavekrav</h1><p>Den faste checkliste er lavet til H3-kvistopgaven.</p></div></div><div class="card" style="padding:20px">Denne sag er ikke markeret som en H3 / Tag & kvist-sag.</div>`;return}
    page.innerHTML='<div class="pagehead"><div><h1>Opgavekrav</h1><p>Henter H3-checkliste og dokumentationsfotos…</p></div></div>';
    const files=await fetchMeta('requirement');window._v4MetaCache=window._v4MetaCache||{};window._v4MetaCache.requirement=files;
    const reqs=p.assignmentRequirements,done=reqs.filter(x=>x.status==='Opfyldt').length,pct=Math.round(done/REQUIREMENTS.length*100);
    page.innerHTML=`<div class="pagehead"><div><h1>Opgavekrav</h1><p>Fast H3-checkliste med mål, kommentar og dokumentation.</p></div><div class="h3-progress"><b>${done}/${REQUIREMENTS.length}</b><div class="h3-progressbar"><span style="width:${pct}%"></span></div><small>${pct}%</small></div></div><div class="h3-intro"><b>Grundlag:</b> 2-mands rytterkvist med tagmateriale der kræver undertag. Her kan I dokumentere de konkrete udførelseskrav fra opgaven. Systemet udfylder ikke mål eller løsninger automatisk.</div><div class="h3-requirements">${REQUIREMENTS.map((def,i)=>{const r=reqs.find(x=>x.key===def.key)||{},photos=files.filter(f=>f.requirement_key===def.key);return `<article class="h3-req ${r.status==='Opfyldt'?'done':r.status==='Afvigelse'?'warn':''}"><div class="h3-req-index">${i+1}</div><div class="h3-req-title"><b>${h(def.title)}</b><small>${h(def.detail)}</small><div class="req-photo-list">${photos.map(f=>`<button class="secondary" onclick="openSharedFileV4('${f.id}')">📷 ${h(f.name.length>18?f.name.slice(0,15)+'…':f.name)}</button>${f.uploaded_by===cloudUser?.id?`<button class="dangerbtn" onclick="deleteRequirementPhotoV4('${f.id}')">×</button>`:''}`).join('')}</div><label style="display:inline-flex;cursor:pointer;margin-top:7px"><span class="mini-btn">+ Foto</span><input type="file" accept="image/*" hidden onchange="uploadRequirementPhotoV4(${i},this)"></label></div><div><label>Status</label><select onchange="reqSetV4(${i},'status',this.value)">${REQ_STATUSES.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="req-measure"><label>${h(def.measure)}</label><input value="${h(r.measure||'')}" placeholder="Skriv mål / resultat" onchange="reqSetV4(${i},'measure',this.value)"></div><div class="req-comment"><label>Kommentar</label><textarea placeholder="Bemærkning, løsning eller afvigelse" onchange="reqSetV4(${i},'comment',this.value)">${h(r.comment||'')}</textarea></div></article>`}).join('')}</div>`;
  };

  /* ----- TEGNINGER ----- */
  pageMap.drawings='drawings-page';
  window.uploadDrawingV4=async function(input){const file=input.files?.[0];if(!file)return;const type=document.getElementById('drawing-type')?.value||DRAWING_TYPES[0],status=document.getElementById('drawing-status')?.value||'Kladde';toast('Uploader tegning…');const row=await uploadShared(file,'drawings',{drawing_type:type,drawing_status:status});if(row){active().drawings.push({sharedId:row.id,path:row.path,name:row.name,type,status});saveState();toast('Tegning gemt');renderDrawingsV4()}};
  window.updateDrawingStatusV4=async function(id,status){const row=(window._v4MetaCache?.drawings||[]).find(x=>x.id===id);if(!row||row.uploaded_by!==cloudUser?.id)return toast('Kun uploaderen kan ændre status');const {error}=await sb.from(META_TABLE).update({drawing_status:status}).eq('id',id);if(error)return toast('Kunne ikke opdatere status');row.drawing_status=status;renderDrawingsV4()};
  window.deleteDrawingV4=async function(id){const row=(window._v4MetaCache?.drawings||[]).find(x=>x.id===id);if(await deleteShared(row)){active().drawings=active().drawings.filter(x=>x.sharedId!==id&&x.path!==row.path);saveState();renderDrawingsV4()}};
  window.renderDrawingsV4=async function(){const p=active();ensureV4(p);const page=document.getElementById('drawings-page');if(!page)return;page.innerHTML='<div class="pagehead"><div><h1>Tegninger</h1><p>Henter skitser og projekttegninger…</p></div></div>';const rows=await fetchMeta('drawings');window._v4MetaCache=window._v4MetaCache||{};window._v4MetaCache.drawings=rows;const approved=rows.filter(x=>x.drawing_status==='Godkendt').length;page.innerHTML=`<div class="pagehead"><div><h1>Tegninger</h1><p>Skitser, projekttegninger og arbejdstegninger med godkendelsesstatus.</p></div><div class="h3-progress"><b>${approved}/${rows.length}</b><span>godkendt</span></div></div><div class="drawing-toolbar"><label>Type<select id="drawing-type">${DRAWING_TYPES.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Status ved upload<select id="drawing-status">${DRAWING_STATUSES.map(x=>`<option>${x}</option>`).join('')}</select></label><label style="cursor:pointer"><span class="primary" style="display:inline-block;padding:10px 14px">+ Upload tegning</span><input type="file" accept="image/*,.pdf,.dwg,.dxf" hidden onchange="uploadDrawingV4(this)"></label></div>${rows.length?`<div class="drawing-grid">${rows.map(r=>`<article class="drawing-card"><div class="drawing-card-top"><div><h3>${h(r.name)}</h3><small>${h(r.drawing_type||'Tegning')} · ${Math.max(1,Math.round((r.size_bytes||0)/1024))} KB</small></div><span class="drawing-status ${r.drawing_status==='Godkendt'?'approved':''}">${h(r.drawing_status||'Kladde')}</span></div><div class="shared-owner">${r.uploaded_by===cloudUser?.id?'Uploadet af dig':'Uploadet af en anden bruger'}</div>${r.uploaded_by===cloudUser?.id?`<select onchange="updateDrawingStatusV4('${r.id}',this.value)">${DRAWING_STATUSES.map(s=>`<option ${s===r.drawing_status?'selected':''}>${s}</option>`).join('')}</select>`:''}<div class="drawing-actions"><button class="secondary" onclick="openSharedFileV4('${r.id}')">Åbn</button>${r.uploaded_by===cloudUser?.id?`<button class="dangerbtn" onclick="deleteDrawingV4('${r.id}')">Slet</button>`:''}</div></article>`).join('')}</div>`:'<div class="card" style="padding:22px;text-align:center">Ingen tegninger uploadet endnu.</div>'}<p class="shared-note">Alle indloggede brugere kan se tegningerne. Kun den bruger der uploadede en fil kan ændre status eller slette den.</p>`};

  /* ----- TEKNISK DOKUMENTATION ----- */
  pageMap.technical='technical-page';
  window.techSetV4=function(key,value){const p=active();ensureV4(p);p.technical[key]=value;saveState(false)};
  window.renderTechnicalV4=function(){const p=active();ensureV4(p);const t=p.technical,filled=Object.keys(TECH_FIELDS).filter(k=>String(t[k]||'').trim()).length;document.getElementById('technical-page').innerHTML=`<div class="pagehead"><div><h1>Teknisk dokumentation</h1><p>Bygningstype, BR-grundlag og begrundelser for projektets løsninger.</p></div><div class="h3-progress"><b>${filled}/${Object.keys(TECH_FIELDS).length}</b><span>felter udfyldt</span></div></div><div class="h3-intro">Udfyld felterne ud fra jeres egne godkendte løsninger og dokumentation. Siden er opbygget efter opgavens fokus på holdbarhed, undertag, tagbeklædning, isolering, styrke, fugt, energi, ventilation og tæthed.</div><div class="tech-summary"><div><span>Bygningstype</span><b>${h(t.buildingType||'Ikke angivet')}</b></div><div><span>Taghældning</span><b>${h(t.roofPitch||'Ikke angivet')}</b></div><div><span>Tagbeklædning</span><b>${h(t.roofMaterial||'Ikke angivet')}</b></div><div><span>U-værdi / energi</span><b>${h(t.uValue||'Ikke angivet')}</b></div></div><div class="tech-grid"><section class="tech-card"><h2>Projektgrundlag</h2><p>Bygningen, eksisterende forhold og energikrav.</p><div class="tech-form">${[['buildingType','Bygningstype'],['existingRoof','Eksisterende tag / konstruktion'],['roofPitch','Taghældning'],['roofMaterial','Tagbeklædning'],['insulationSolution','Isoleringsopbygning'],['uValue','U-værdi / energidokumentation'],['brDocumentation','BR / krav og dokumentation']].map(([k,l])=>`<div class="tech-field"><label>${l}</label><textarea onchange="techSetV4('${k}',this.value)" placeholder="Skriv jeres dokumentation her">${h(t[k]||'')}</textarea></div>`).join('')}</div></section><section class="tech-card"><h2>Valg og begrundelser</h2><p>Forklar hvorfor løsningerne er valgt og hvilke konsekvenser de har.</p><div class="tech-form">${[['undertagReason','Undertag – valg og begrundelse'],['roofCoveringReason','Tagbeklædning – valg og begrundelse'],['insulationReason','Isolering – valg og begrundelse'],['strength','Styrke, fastgørelse og afstivning'],['moisture','Fugt og vandførende detaljer'],['energy','Energi og kuldebroer'],['ventilationTightness','Ventilation, dampspærre og tæthed'],['alternatives','Alternative løsninger og konsekvenser']].map(([k,l])=>`<div class="tech-field"><label>${l}</label><textarea onchange="techSetV4('${k}',this.value)" placeholder="Begrund løsning, udførelse og konsekvenser">${h(t[k]||'')}</textarea></div>`).join('')}</div></section></div>`};

  /* ----- ANSVARSFORDELING I TIDSPLAN ----- */
  window.setTeamMemberV4=function(index,value){const p=active();ensureV4(p);p.teamMembers[index]=value||`Person ${index+1}`;saveState(false);renderSchedule()};
  window.setResponsibleV4=function(index,value){const p=active();ensureV4(p);p.schedule.tasks[index].responsible=value;saveState(false);renderSchedule()};
  function renderScheduleV4(){
    const p=active();ensureV4(p);const s=p.schedule,rows=scheduleRows(),total=s.tasks.reduce((a,x)=>a+Number(x.hours||0),0),end=[...rows].reverse().find(x=>x.end)?.end,m1=p.teamMembers[0]||'Person 1',m2=p.teamMembers[1]||'Person 2';
    document.getElementById('schedule-page').innerHTML=`<div class="pagehead"><div><h1>Tidsplan</h1><p>Planlæg mandetimer og fordel ansvaret mellem de to personer.</p></div><div><button class="secondary" onclick="hoursFromCalc()">Hent timer fra kalkulation</button> <button class="primary" onclick="smartHours()">⚡ Smart fordel timer</button></div></div><div class="team-settings"><label>Person 1<input value="${h(m1)}" onchange="setTeamMemberV4(0,this.value)"></label><label>Person 2<input value="${h(m2)}" onchange="setTeamMemberV4(1,this.value)"></label><small>Vælg ansvarlig på hver aktivitet: én person eller begge.</small></div><div class="schedule-settings card"><div class="field"><label>Projektstart</label><input type="date" value="${s.startDate}" onchange="sset('startDate',this.value)"></div><div class="field"><label>Timer pr. dag</label><input type="number" step=".1" value="${s.dayHours}" onchange="sset('dayHours',this.value)"></div><div class="field"><label>Arbejdsstart</label><input type="time" value="${s.workStart}" onchange="sset('workStart',this.value)"></div><div class="field"><label>Mandetimer</label><input type="number" step=".25" value="${s.budgetHours||''}" onchange="sset('budgetHours',this.value)"></div></div><div class="metrics"><article class="card metric"><span>Planlagt</span><strong>${num(total,2)} t.</strong></article><article class="card metric"><span>Beregnet slut</span><strong>${end?end.toLocaleDateString('da-DK'):'—'}</strong></article></div><section class="card schedule-card"><div class="schedule-table"><div class="schedule-row head v4"><span>Aktivitet</span><span>Vægt</span><span>Mandetimer</span><span>Personer</span><span>Ansvarlig</span><span>Plan</span><span>Varighed</span><span>Start</span><span>Slut</span><span></span></div>${rows.map((r,i)=>{const resp=s.tasks[i].responsible||'both';return `<div class="schedule-row v4"><input class="task-name" value="${h(r.name)}" onchange="tset(${i},'name',this.value)"><input type="number" value="${r.weight}" onchange="tset(${i},'weight',this.value)"><input type="number" step=".25" value="${r.hours||0}" onchange="tset(${i},'hours',this.value)"><input type="number" value="${r.crew}" onchange="tset(${i},'crew',this.value)"><select onchange="setResponsibleV4(${i},this.value)"><option value="both" ${resp==='both'?'selected':''}>Begge</option><option value="p1" ${resp==='p1'?'selected':''}>${h(m1)}</option><option value="p2" ${resp==='p2'?'selected':''}>${h(m2)}</option></select><span>Efter forrige</span><b>${r.clock?num(r.clock,2)+' t.':'—'}</b><span>${fmtD(r.start)}</span><span>${fmtD(r.end)}</span><button class="del" onclick="active().schedule.tasks.splice(${i},1);saveState(false);renderSchedule()">×</button></div>`}).join('')}</div></section>`;
  }
  renderSchedule=renderScheduleV4;window.renderSchedule=renderScheduleV4;

  /* ----- FÆLLES DOKUMENTER: metadata synlig for alle brugere ----- */
  async function backfillLocalDocs(){const p=active();if(!sb||!cloudUser||!p.documents?.length)return;const rows=await fetchMeta('documents'),paths=new Set(rows.map(x=>x.path));for(const d of p.documents){if(!d.path||paths.has(d.path)||!d.path.startsWith(cloudUser.id+'/'))continue;const {error}=await sb.from(META_TABLE).insert({project_ref:p.id,category:'documents',name:d.name||d.path.split('/').pop(),path:d.path,mime_type:d.type||'',size_bytes:d.size||0,uploaded_by:cloudUser.id});if(!error)paths.add(d.path)}}
  window.uploadProjectDocument=async function(input){const file=input.files?.[0];if(!file)return;toast('Uploader dokument…');const row=await uploadShared(file,'documents');if(!row)return;active().documents=active().documents||[];active().documents.push({id:uid('d'),sharedId:row.id,name:row.name,path:row.path,type:row.mime_type,size:row.size_bytes,createdAt:row.created_at});saveState();toast('Dokument gemt');renderDocuments()};
  window.deleteSharedDocumentV4=async function(id){const row=(window._v4MetaCache?.documents||[]).find(x=>x.id===id);if(await deleteShared(row)){active().documents=(active().documents||[]).filter(x=>x.path!==row.path);saveState();renderDocuments()}};
  window.renderDocuments=async function(){const p=active();ensureV4(p);const page=document.getElementById('documents-page');if(!page)return;page.innerHTML='<div class="pagehead"><div><h1>Dokumenter</h1><p>Henter fælles sagsfiler…</p></div></div>';await backfillLocalDocs();const rows=await fetchMeta('documents');window._v4MetaCache=window._v4MetaCache||{};window._v4MetaCache.documents=rows;page.innerHTML=`<div class="pagehead"><div><h1>Dokumenter</h1><p>Fælles arbejdstegninger, tilbud, montagevejledninger, billeder og øvrige sagsfiler.</p></div></div><label class="doc-drop"><strong>+ Upload dokument</strong><small>Alle indloggede brugere kan se filen · maks. 25 MB</small><input type="file" hidden onchange="uploadProjectDocument(this)"></label>${rows.length?`<div class="doc-grid">${rows.map(d=>`<article class="doc-card"><div><h3>${h(d.name)}</h3><p>${h(d.mime_type||'Fil')} · ${Math.max(1,Math.round((d.size_bytes||0)/1024))} KB</p><small class="shared-owner">${d.uploaded_by===cloudUser?.id?'Uploadet af dig':'Uploadet af en anden bruger'}</small></div><div class="doc-actions"><button class="secondary" onclick="openSharedFileV4('${d.id}')">Åbn</button>${d.uploaded_by===cloudUser?.id?`<button class="dangerbtn" onclick="deleteSharedDocumentV4('${d.id}')">Slet</button>`:''}</div></article>`).join('')}</div>`:'<div class="card" style="padding:22px;text-align:center">Ingen dokumenter på sagen endnu.</div>'}<div class="report-grid"><article class="report-card"><h3>KS-rapport</h3><p>Status, kommentarer og kontrolpunkter.</p><button class="secondary" onclick="printReportV3('ks')">Udskriv / PDF</button></article><article class="report-card"><h3>Timeregnskab</h3><p>Registrerede timer fordelt på opgaver.</p><button class="secondary" onclick="printReportV3('hours')">Udskriv / PDF</button></article><article class="report-card"><h3>Kalkulation</h3><p>Materialer, arbejdsløn og samlet økonomi.</p><button class="secondary" onclick="printReportV3('calc')">Udskriv / PDF</button></article><article class="report-card"><h3>Samlet sagsrapport</h3><p>Sagsdata, økonomi, timer og KS i én rapport.</p><button class="primary" onclick="printReportV3('full')">Udskriv / PDF</button></article></div>`};

  /* ----- FREMLÆGGELSE: direkte kobling til dokumentationen ----- */
  const oldPresentation=renderPresentation;
  function renderPresentationV4(){ensureV4(active());oldPresentation();const page=document.getElementById('presentation-page'),head=page?.querySelector('.pagehead');if(!page||!head)return;const p=active(),reqs=p.assignmentRequirements||[],done=reqs.filter(x=>x.status==='Opfyldt').length,techFilled=Object.keys(TECH_FIELDS).filter(k=>String(p.technical?.[k]||'').trim()).length,photos=(p.ks||[]).reduce((a,k)=>a+(k.photos?.length||0),0);const panel=document.createElement('div');panel.className='presentation-source-panel';panel.innerHTML=`<div><div><h3>Fremlæggelsesgrundlag</h3><p>Hop direkte til den dokumentation du kan bruge i præsentationen.</p></div><small id="presentation-drawing-count">Tegninger: …</small></div><div class="source-chips"><button class="source-chip" onclick="go('requirements')"><span>Opgavekrav</span><b>${done}/${REQUIREMENTS.length} opfyldt</b></button><button class="source-chip" onclick="go('drawings')"><span>Tegninger</span><b id="presentation-approved-drawings">Henter…</b></button><button class="source-chip" onclick="go('technical')"><span>Teknisk dokumentation</span><b>${techFilled}/${Object.keys(TECH_FIELDS).length} udfyldt</b></button><button class="source-chip" onclick="go('ks')"><span>KS & fotos</span><b>${photos} foto${photos===1?'':'s'}</b></button></div>`;head.insertAdjacentElement('afterend',panel);fetchMeta('drawings').then(rows=>{const approved=rows.filter(x=>x.drawing_status==='Godkendt').length,el=document.getElementById('presentation-approved-drawings'),count=document.getElementById('presentation-drawing-count');if(el)el.textContent=`${approved}/${rows.length} godkendt`;if(count)count.textContent=`Tegninger: ${rows.length}`})}
  renderPresentation=renderPresentationV4;window.renderPresentation=renderPresentationV4;

  /* Route de tre nye sider uden at ændre den oprindelige app-struktur. */
  const previousRenderPage=renderPage;
  renderPage=function(page){ensureV4(active());if(page==='requirements')return renderRequirementsV4();if(page==='drawings')return renderDrawingsV4();if(page==='technical')return renderTechnicalV4();return previousRenderPage(page)};
  window.renderPage=renderPage;

  setTimeout(()=>{(state.projects||[]).forEach(ensureV4);document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));renderAll()},80);
})();
